### Para usar estas request, debe instalar la extesión de vs code: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

# RENDER - DEPLOY
# @baseUrl = https://crud-node-tiendaveh.onrender.com/api/v1

# DOCKER
# @baseUrl = https://walrus-delicate-routinely.ngrok-free.app/api/v1

# LOCAL
 @baseUrl = http://localhost:3001/api/v1

### get all
GET {{baseUrl}}/vehiculos
Content-Type: application/json

### get by id / validacion confirmada - el id debe ser numerico
GET {{baseUrl}}/vehiculos/1
Content-Type: application/json

### create / validacion confirmada - impide duplicado de placas
POST {{baseUrl}}/vehiculos
Content-Type: application/json

{
  "marca": "Honda",
  "modelo": "Civic",
  "color": "Azul",
  "precio": 23001.00,
  "placa": "XYZ-789"
}

### update / validacion confirmada - impide duplicado de placas
PATCH {{baseUrl}}/vehiculos/4
Content-Type: application/json

{
  "marca": "Toyota",
  "modelo": "Corolla",
  "color": "verde",
  "precio": 15001.50,
  "placa": "ABC-456"
}

### delete / validacion confirmada - el id debe ser numerico
DELETE {{baseUrl}}/vehiculos/3
Content-Type: application/json